version: '3.7'
services:
  portainer:
    image: portainer/portainer-ce

  agent:
    image: consul:latest

  zoo1:
    image: confluentinc/cp-zookeeper:latest

  kafka1:
    image: confluentinc/cp-kafka:latest

  db:
    image: mysql:latest

volumes:
  portainer_data:
  db:
    driver: local

