version: '3.7'
services:
  agent:
    image: consul:latest

  zoo1:
    image: confluentinc/cp-zookeeper:latest

  kafka1:
    image: confluentinc/cp-kafka:latest

  db:
    image: mysql:latest

  jaeger:
    image: jaegertracing/all-in-one:latest

  prometheus:
    image: prom/prometheus

  alertmanager:
    image: prom/alertmanager

  grafana:
    image: grafana/grafana-oss

volumes:
  db:
    driver: local
  prometheus_data:

networks:
  go-movie:
    name: go-movie