version: '3.7'


services:
  metadata:
    image: ashkanmaleki/metadata:1.0.0
    container_name: metadata
    hostname: metadata
#    build:
#      context: .
##      dockerfile: ../../dockerfile/Dockerfile
#      dockerfile: ../../dockerfile/Dockerfile-test
#      args:
#        service: metadata
    expose:
      - '8081'
    environment:
      ENVIRONMENT: development
      SERVICE_DISCOVERY_URL: "consul-agent:8500"
      http_server_port: 8081
      prometheus_metrics_port: 8091
    depends_on:
      - db
      - agent
      - zoo1
      - kafka1
#    command: [ "/movie/service" ]

  movie:
    container_name: movie
    hostname: movie
    build:
      context: .
#      dockerfile: ../../dockerfile/Dockerfile
      dockerfile: ../../dockerfile/Dockerfile-test
      args:
        service: movie
    expose:
      - '8083'
    environment:
      ENVIRONMENT: development
      CONFIG_FILE: "movie/base.yaml"
      SERVICE_DISCOVERY_URL: "consul-agent:8500"
    depends_on:
      - db
      - agent
      - zoo1
      - kafka1
#    command: [ "/movie/service" ]

  rating:
    container_name: rating
    hostname: rating
    build:
      context: .
#      dockerfile: ../../dockerfile/Dockerfile-csg-enabled
      dockerfile: ../../dockerfile/Dockerfile-test
      args:
        service: rating
    expose:
      - '8082'
    environment:
      ENVIRONMENT: development
      CONFIG_FILE: "movie/base.yaml"
      SERVICE_DISCOVERY_URL: "consul-agent:8500"
      KAFKA_ADDRESS: "kafka1:19092"
    depends_on:
      - db
      - agent
      - zoo1
      - kafka1
#    command: [ "/movie/service" ]