version: '3.7'


services:
  metadata:
    container_name: metadata
    hostname: metadata
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        service: metadata
    expose:
      - '8081'
    environment:
      ENVIRONMENT: development
      CONFIG_FILE: "movie/base.yaml"
      SERVICE_DISCOVERY_URL: "consul-agent:8500"
    depends_on:
      - db
      - agent
      - zoo1
      - kafka1
    command: [ "/movie/service" ]

  movie:
    container_name: movie
    hostname: movie
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        service: movie
    expose:
      - '8083'
    environment:
      ENVIRONMENT: development
      CONFIG_FILE: "movie/base.yaml"
      SERVICE_DISCOVERY_URL: "consul-agent:8500"
    depends_on:
      - db
      - agent
      - zoo1
      - kafka1
    command: [ "/movie/service" ]

  rating:
    container_name: rating
    hostname: rating
    build:
      context: .
      dockerfile: docker/Dockerfile-csg-enabled
      args:
        service: rating
    expose:
      - '8082'
    environment:
      ENVIRONMENT: development
      CONFIG_FILE: "movie/base.yaml"
      SERVICE_DISCOVERY_URL: "consul-agent:8500"
      KAFKA_ADDRESS: "kafka1:19092"
    depends_on:
      - db
      - agent
      - zoo1
      - kafka1
    command: [ "/movie/service" ]